### ISSUE TITLE
EXTRACT VARIABLES FROM TEMPLATE

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/sweatShop-creator#1]
THE EXEPECTED RESULT FROM THE EXAMPLE CODE SHOULD BE WORK W/ EVERY GOLANG TEMPLATE STRING (renderedJobManifest)

```
package main

import (
	"fmt"
	"regexp"
)

const renderedJobManifest = `
apiVersion: batch/v1
kind: {{ .Kind }}
metadata:
  name: {{ .Name }}
  namespace: machine-shop-{{ .Name }}
`

func main() {

	foundVarsInRegex := GetAllRegexMatches(renderedJobManifest, `\{\{(.*?)\}\}`)
	fmt.Println(foundVarsInRegex)

	// REMOVE BRACKETS
	// REMOVE DOT
	// REMOVE DUPLICATES

	expectedResult := []string{"Kind", "Name"}
	fmt.Println("\n\n\nEXPECTED RESULT - ALL VAR NAMES FROM TEMPLATE:")

	for _, variable := range expectedResult {
		fmt.Println(variable)
	}

}

func GetAllRegexMatches(scanText, regexPattern string) []string {

	re := regexp.MustCompile(regexPattern)

	return re.FindAllString(scanText, -1)
}

```

**Comment by patrick-hermann-sva** [comment]
whatever template we have/give to the code/function we want to have back a slice/list with all the variable names (but no duplicates)

**Comment by patrick-hermann-sva** [comment]
example strip 

```
t := strings.Trim(variable, "{{ .")
```

**Comment by patrick-hermann-sva** [comment]
google e.g. golang remove duplicates from slice

**Comment by ankitsharma12-ops** [comment]
below snip is giving the expected results:
package main

import (
	"fmt"
	"regexp"
	"strings"
)

const renderedJobManifest = `
apiVersion: batch/v1
kind: {{ .Kind }}
metadata:
  name: {{ .Name }}
  namespace: machine-shop-{{ .Name }}
`

func main() {

	foundVarsInRegex := GetAllRegexMatches(renderedJobManifest, `\{\{(.*?)\}\}`)

results := make([]string, len(foundVarsInRegex))
	for _, variable := range foundVarsInRegex {

		t := strings.Trim(variable, "{{ .")
		t = strings.Trim(t, " }}")

		results = append(results, t)
	}

	resultWithDups := removeDuplicateStr(results)

		for _, variable := range resultWithDups {
			fmt.Println(variable)
		}


}

func removeDuplicateStr(results []string) []string {
    allKeys := make(map[string]bool)
    list := []string{}
    for _, item := range results {
        if _, value := allKeys[item]; !value {
            allKeys[item] = true
            list = append(list, item)
        }
    }
    return list
}
func GetAllRegexMatches(scanText, regexPattern string) []string {

	re := regexp.MustCompile(regexPattern)

	return re.FindAllString(scanText, -1)
}

**Comment by ankitsharma12-ops** [comment]
`package main

import (
	"fmt"
	"regexp"
	"strings"
)

const renderedJobManifest = `
apiVersion: batch/v1
kind: {{ .Kind }}
metadata:
  name: {{ .Name }}
  namespace: machine-shop-{{ .Name }}
`

func main() {

	foundVarsInRegex := GetAllRegexMatches(renderedJobManifest, `\{\{(.*?)\}\}`)

results := make([]string, len(foundVarsInRegex))
	for _, variable := range foundVarsInRegex {

		t := strings.Trim(variable, "{{ .")
		t = strings.Trim(t, " }}")

		results = append(results, t)
	}

	resultWithDups := removeDuplicateStr(results)

		for _, variable := range resultWithDups {
			fmt.Println(variable)
		}


}

func removeDuplicateStr(results []string) []string {
    allKeys := make(map[string]bool)
    list := []string{}
    for _, item := range results {
        if _, value := allKeys[item]; !value {
            allKeys[item] = true
            list = append(list, item)
        }
    }
    return list
}
func GetAllRegexMatches(scanText, regexPattern string) []string {

	re := regexp.MustCompile(regexPattern)

	return re.FindAllString(scanText, -1)
}
`

**Comment by patrick-hermann-sva** [comment]
great workd @ankitsharma12-ops !
